export const BUSINESS_CONTACT = {
  email: "nospam@example.org", // Scrambled for protection
  phone: "555-000-1234", // Scrambled for protection
  phoneSecondary: "555-000-5678", // Scrambled for protection
  phoneNumeric: "5550001234",
  address: "Wallington, NJ 07057",
  businessName: "CSR Realty Appraisers",
  tagline: "New Jersey's Trusted Real Estate Appraisal Experts",
  owner: "Albert Zaccone, Certified Appraiser",
  hours: "Monday to Sunday, 9:00 AM - 8:00 PM",
  serviceArea: "All of New Jersey",
} as const;

// Real contact info (not exported to avoid accidental use)
const REAL_CONTACT = {
  email: "al@csrappraisals.com",
  phone: "(201) 815-1000",
  phoneSecondary: "(973) 591-9990",
} as const;

export interface CountyCoverage {
  county: string;
  municipalities: string[];
}

export const NJ_COVERAGE: CountyCoverage[] = [
  {
    county: "Bergen",
    municipalities: [
      "Allendale",
      "Alpine",
      "Bergenfield",
      "Bogota",
      "Carlstadt",
      "Cliffside Park",
      "Closter",
      "Cresskill",
      "Demarest",
      "Dumont",
      "East Rutherford",
      "Edgewater",
      "Elmwood Park",
      "Emerson",
      "Englewood",
      "Englewood Cliffs",
      "Fair Lawn",
      "Fairview",
      "Fort Lee",
      "Franklin Lakes",
      "Garfield",
      "Glen Rock",
      "Hackensack",
      "Harrington Park",
      "Hasbrouck Heights",
      "Haworth",
      "Hillsdale",
      "Ho-Ho-Kus",
      "Leonia",
      "Little Ferry",
      "Lodi",
      "Lyndhurst",
      "Mahwah",
      "Maywood",
      "Midland Park",
      "Montvale",
      "Moonachie",
      "New Milford",
      "North Arlington",
      "Northvale",
      "Norwood",
      "Oakland",
      "Old Tappan",
      "Oradell",
      "Palisades Park",
      "Paramus",
      "Park Ridge",
      "Ramsey",
      "Ridgefield",
      "Ridgefield Park",
      "Ridgewood",
      "River Edge",
      "River Vale",
      "Rochelle Park",
      "Rockleigh",
      "Rutherford",
      "Saddle Brook",
      "Saddle River",
      "South Hackensack",
      "Teaneck",
      "Tenafly",
      "Teterboro",
      "Upper Saddle River",
      "Waldwick",
      "Wallington",
      "Washington Township",
      "Westwood",
      "Woodcliff Lake",
      "Wood-Ridge",
      "Wyckoff",
    ],
  },
  {
    county: "Essex",
    municipalities: [
      "Belleville",
      "Bloomfield",
      "Caldwell",
      "Cedar Grove",
      "East Orange",
      "Essex Fells",
      "Fairfield",
      "Glen Ridge",
      "Irvington",
      "Livingston",
      "Maplewood",
      "Millburn",
      "Montclair",
      "Newark",
      "North Caldwell",
      "Nutley",
      "Orange",
      "Roseland",
      "South Orange",
      "Verona",
      "West Caldwell",
      "West Orange",
    ],
  },
  {
    county: "Hudson",
    municipalities: [
      "Bayonne",
      "East Newark",
      "Guttenberg",
      "Harrison",
      "Hoboken",
      "Jersey City",
      "Kearny",
      "North Bergen",
      "Secaucus",
      "Union City",
      "Weehawken",
      "West New York",
    ],
  },
  {
    county: "Hunterdon",
    municipalities: [
      "Alexandria Township",
      "Bethlehem Township",
      "Bloomsbury",
      "Califon",
      "Clinton (Town)",
      "Clinton Township",
      "Delaware Township",
      "East Amwell Township",
      "Flemington",
      "Franklin Township",
      "Frenchtown",
      "Glen Gardner",
      "Hampton",
      "High Bridge",
      "Holland Township",
      "Kingwood Township",
      "Lambertville",
      "Lebanon (Borough)",
      "Lebanon Township",
      "Milford",
      "Raritan Township",
      "Readington Township",
      "Stockton",
      "Tewksbury Township",
      "Union Township",
      "West Amwell Township",
    ],
  },
  {
    county: "Middlesex",
    municipalities: [
      "Carteret",
      "East Brunswick",
      "Edison",
      "Helmetta",
      "Highland Park",
      "Jamesburg",
      "Metuchen",
      "Middlesex (Borough)",
      "Milltown",
      "Monroe Township",
      "New Brunswick",
      "North Brunswick",
      "Old Bridge Township",
      "Perth Amboy",
      "Piscataway",
      "Plainsboro Township",
      "Sayreville",
      "South Amboy",
      "South Brunswick",
      "South Plainfield",
      "South River",
      "Spotswood",
      "Woodbridge Township",
    ],
  },
  {
    county: "Monmouth",
    municipalities: [
      "Aberdeen Township",
      "Allenhurst",
      "Allentown",
      "Asbury Park",
      "Atlantic Highlands",
      "Avon-by-the-Sea",
      "Belmar",
      "Bradley Beach",
      "Brielle",
      "Colts Neck Township",
      "Deal",
      "Eatontown",
      "Englishtown",
      "Fair Haven",
      "Farmingdale",
      "Freehold (Borough)",
      "Freehold Township",
      "Hazlet Township",
      "Highlands",
      "Holmdel Township",
      "Howell Township",
      "Interlaken",
      "Keansburg",
      "Keyport",
      "Little Silver",
      "Loch Arbour",
      "Long Branch",
      "Manalapan Township",
      "Manasquan",
      "Marlboro Township",
      "Matawan",
      "Middletown Township",
      "Millstone Township",
      "Monmouth Beach",
      "Neptune City",
      "Neptune Township",
      "Ocean Township",
      "Oceanport",
      "Red Bank",
      "Roosevelt",
      "Rumson",
      "Sea Bright",
      "Sea Girt",
      "Shrewsbury (Borough)",
      "Shrewsbury Township",
      "Spring Lake",
      "Spring Lake Heights",
      "Tinton Falls",
      "Union Beach",
      "Upper Freehold Township",
      "Wall Township",
      "West Long Branch",
    ],
  },
  {
    county: "Morris",
    municipalities: [
      "Boonton",
      "Boonton Township",
      "Butler",
      "Chatham (Borough)",
      "Chatham Township",
      "Chester (Borough)",
      "Chester Township",
      "Denville Township",
      "Dover",
      "East Hanover Township",
      "Florham Park",
      "Hanover Township",
      "Harding Township",
      "Jefferson Township",
      "Kinnelon",
      "Lincoln Park",
      "Long Hill Township",
      "Madison",
      "Mendham (Borough)",
      "Mendham Township",
      "Mine Hill Township",
      "Montville Township",
      "Morris Plains",
      "Morris Township",
      "Morristown",
      "Mount Arlington",
      "Mount Olive Township",
      "Mountain Lakes",
      "Netcong",
      "Parsippany-Troy Hills Township",
      "Pequannock Township",
      "Randolph",
      "Riverdale",
      "Rockaway (Borough)",
      "Rockaway Township",
      "Roxbury Township",
      "Victory Gardens",
      "Washington Township",
      "Wharton",
    ],
  },
  {
    county: "Passaic",
    municipalities: [
      "Bloomingdale",
      "Clifton",
      "Haledon",
      "Hawthorne",
      "Little Falls",
      "North Haledon",
      "Passaic",
      "Paterson",
      "Pompton Lakes",
      "Prospect Park",
      "Ringwood",
      "Totowa",
      "Wanaque",
      "Wayne",
      "West Milford",
      "Woodland Park",
    ],
  },
  {
    county: "Somerset",
    municipalities: [
      "Bedminster Township",
      "Bernards Township",
      "Bernardsville",
      "Bound Brook",
      "Branchburg Township",
      "Bridgewater Township",
      "Far Hills",
      "Franklin Township",
      "Green Brook Township",
      "Hillsborough Township",
      "Manville",
      "Millstone (Borough)",
      "Montgomery Township",
      "North Plainfield",
      "Peapack and Gladstone",
      "Raritan (Borough)",
      "Rocky Hill",
      "Somerville",
      "South Bound Brook",
      "Warren Township",
      "Watchung",
    ],
  },
  {
    county: "Sussex",
    municipalities: [
      "Andover (Borough)",
      "Andover Township",
      "Branchville",
      "Byram Township",
      "Frankford Township",
      "Franklin (Borough)",
      "Fredon Township",
      "Green Township",
      "Hamburg",
      "Hampton Township",
      "Hardyston Township",
      "Hopatcong",
      "Lafayette Township",
      "Montague Township",
      "Newton",
      "Ogdensburg",
      "Sandyston Township",
      "Sparta Township",
      "Stanhope",
      "Stillwater Township",
      "Sussex (Borough)",
      "Vernon Township",
      "Wantage Township",
    ],
  },
  {
    county: "Union",
    municipalities: [
      "Berkeley Heights",
      "Clark",
      "Cranford",
      "Elizabeth",
      "Fanwood",
      "Garwood",
      "Hillside",
      "Kenilworth",
      "Linden",
      "Mountainside",
      "New Providence",
      "Plainfield",
      "Rahway",
      "Roselle",
      "Roselle Park",
      "Scotch Plains",
      "Springfield Township",
      "Summit",
      "Union Township",
      "Westfield",
      "Winfield Township",
    ],
  },
  {
    county: "Warren",
    municipalities: [
      "Allamuchy Township",
      "Alpha",
      "Belvidere",
      "Blairstown Township",
      "Franklin Township",
      "Frelinghuysen Township",
      "Greenwich Township",
      "Hackettstown",
      "Hardwick Township",
      "Harmony Township",
      "Hope Township",
      "Independence Township",
      "Knowlton Township",
      "Liberty Township",
      "Lopatcong Township",
      "Mansfield Township",
      "Oxford Township",
      "Phillipsburg",
      "Pohatcong Township",
      "Washington (Borough)",
      "Washington Township",
      "White Township",
    ],
  },
  {
    county: "Mercer",
    municipalities: [
      "East Windsor Township",
      "Ewing Township",
      "Hamilton Township",
      "Hightstown",
      "Hopewell (Borough)",
      "Hopewell Township",
      "Lawrence Township",
      "Pennington",
      "Princeton",
      "Robbinsville Township",
      "Trenton",
      "West Windsor Township",
    ],
  },
];
